import type { ComponentType, SVGProps } from 'react';
import {
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  Bell,
  BellOff,
  Calendar,
  CalendarClock,
  Camera,
  Check,
  ChevronDown,
  CircleAlert,
  CircleHelp,
  CreditCard,
  Download,
  Edit3,
  Eye,
  EyeOff,
  Folder,
  Heart,
  HeartOff,
  Home,
  Image as ImageIcon,
  Info,
  Lock,
  LockOpen,
  Mail,
  MapPin,
  Menu,
  MoreHorizontal,
  MoreVertical,
  Paperclip,
  Phone,
  PhoneCall,
  Plus,
  Printer,
  RefreshCcw,
  Search,
  Send,
  Settings,
  Share2,
  ShoppingCart,
  Star,
  StarHalf,
  StarOff,
  Trash2,
  Upload,
  User,
  UserCircle,
  X,
} from 'lucide-react';
import type { IconName, IconProps } from '@a2ui/protocol';
import { useBoundString } from '@a2ui/runtime/react';
import type { CatalogComponentProps } from '../catalog.js';

const ICON_MAP: Record<IconName, ComponentType<SVGProps<SVGSVGElement>>> = {
  accountCircle: UserCircle,
  add: Plus,
  arrowBack: ArrowLeft,
  arrowForward: ArrowRight,
  attachFile: Paperclip,
  calendarToday: Calendar,
  call: PhoneCall,
  camera: Camera,
  check: Check,
  close: X,
  delete: Trash2,
  download: Download,
  edit: Edit3,
  event: CalendarClock,
  error: CircleAlert,
  favorite: Heart,
  favoriteOff: HeartOff,
  folder: Folder,
  help: CircleHelp,
  home: Home,
  info: Info,
  locationOn: MapPin,
  lock: Lock,
  lockOpen: LockOpen,
  mail: Mail,
  menu: Menu,
  moreVert: MoreVertical,
  moreHoriz: MoreHorizontal,
  notificationsOff: BellOff,
  notifications: Bell,
  payment: CreditCard,
  person: User,
  phone: Phone,
  photo: ImageIcon,
  print: Printer,
  refresh: RefreshCcw,
  search: Search,
  send: Send,
  settings: Settings,
  share: Share2,
  shoppingCart: ShoppingCart,
  star: Star,
  starHalf: StarHalf,
  starOff: StarOff,
  upload: Upload,
  visibility: Eye,
  visibilityOff: EyeOff,
  warning: AlertTriangle,
};

const FALLBACK = ChevronDown;

export function Icon({ props }: CatalogComponentProps<IconProps>) {
  const name = useBoundString(props.name) as IconName | undefined;
  const Comp = (name && ICON_MAP[name]) ?? FALLBACK;
  return <Comp className="w-4 h-4 inline-block align-middle" />;
}
